In [21]:
from bs4 import BeautifulSoup
import pandas as pd
import os
from requests_html import HTMLSession
import requests

In [8]:
data=pd.read_csv("~/Downloads/E0.csv")

In [85]:
listofteams= data['HomeTeam'].unique()

In [99]:
def scrape_premier_league_logos():
    url = "https://www.premierleague.com/clubs?se=274"
    response = requests.get(url)

    if response.status_code == 200:
        soup = BeautifulSoup(response.text, 'html.parser')

        # Assuming logos are inside a specific class
        logo_elements = soup.find_all('div', class_='clubBadgeContainer')

        # Create a list to store logo URLs
        logos = []

        for logo_element in logo_elements:
            # Assuming logos are stored as background images in the style attribute
             img_element = logo_element.find('img')
             if img_element:
                logo_url = img_element['src']
                logos.append(logo_url)

        return logos
    else:
        print(f"Failed to fetch page. Status code: {response.status_code}")
        return None

In [100]:
# Example usage
premier_league_logos = scrape_premier_league_logos()
if premier_league_logos:
    print("Premier League Logos:")
    for logo in premier_league_logos:
        print(logo)

In [101]:
url = "https://www.premierleague.com/clubs?se=274"
response = requests.get(url)

if response.status_code == 200:
    soup = BeautifulSoup(response.text, 'html.parser')

    # Assuming logos are inside a specific class
    logo_elements = soup.find_all('div', class_='club-card__badge')

    # Create a list to store logo URLs
    logos = []

In [102]:
for logo_element in logo_elements:
    # Assuming logos are stored as background images in the style attribute
        img_element = logo_element.find('img')
        if img_element:
            logo_url = img_element['src']
            logos.append(logo_url)

In [87]:
listofteams = sorted(listofteams)

In [104]:
clubs= pd.DataFrame(data={"Team":listofteams, "Logo":logos} )
clubs.to_csv("clubs.csv")

In [113]:
data.describe(include="all")

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
count,380,380,380,380,380,380.000000,380.000000,380,380.000000,380.000000,...,380.000000,380.000000,380.000000,380.000000,380.000000,380.000000,380.000000,380.000000,380.000000,380.000000
unique,1,115,15,20,20,NaN,NaN,3,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,E0,26/07/2020,15:00,Liverpool,Norwich,NaN,NaN,H,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,380,10,123,19,19,NaN,NaN,172,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,NaN,NaN,NaN,1.515789,1.205263,NaN,0.700000,0.550000,...,2.174132,-0.276974,1.944474,1.960526,1.961053,1.972947,2.013368,2.026921,1.936079,1.950842
std,NaN,NaN,NaN,NaN,NaN,1.248646,1.200252,NaN,0.886427,0.758505,...,0.544434,0.978376,0.129753,0.101650,0.140680,0.105627,0.138995,0.110237,0.127354,0.098890
min,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,NaN,0.000000,0.000000,...,1.450000,-3.750000,1.670000,1.270000,1.710000,1.300000,1.800000,1.300000,1.700000,1.280000
25%,NaN,NaN,NaN,NaN,NaN,1.000000,0.000000,NaN,0.000000,0.000000,...,1.800000,-0.750000,1.870000,1.890000,1.880000,1.890000,1.930000,1.950000,1.860000,1.880000
50%,NaN,NaN,NaN,NaN,NaN,1.000000,1.000000,NaN,0.000000,0.000000,...,2.040000,-0.250000,1.950000,1.970000,1.960000,1.970000,2.000000,2.030000,1.930000,1.950000
75%,NaN,NaN,NaN,NaN,NaN,2.000000,2.000000,NaN,1.000000,1.000000,...,2.400000,0.250000,2.020000,2.040000,2.032500,2.050000,2.070000,2.100000,2.000000,2.020000
max,NaN,NaN,NaN,NaN,NaN,8.000000,9.000000,NaN,5.000000,5.000000,...,5.770000,3.000000,3.550000,2.200000,3.930000,2.290000,3.950000,2.300000,3.660000,2.240000

In [ ]:
data